# Marker Gene DB Template Extractor

Extracts marker gene db ROBOT template from the Human brain atlas all non-neuronal cells anndata (https://cellxgene.cziscience.com/collections/283d65eb-dd53-496d-adb7-7570c7caa443).

In [5]:
import sys
!{sys.executable} -m pip install pandas
!{sys.executable} -m pip install anndata

import os
import pandas as pd
import anndata as ad

Collecting pandas
  Using cached pandas-2.1.1-cp39-cp39-macosx_11_0_arm64.whl (10.9 MB)
Collecting pytz>=2020.1
  Using cached pytz-2023.3.post1-py2.py3-none-any.whl (502 kB)
Collecting numpy>=1.22.4
  Using cached numpy-1.26.1-cp39-cp39-macosx_11_0_arm64.whl (14.0 MB)
Collecting tzdata>=2022.1
  Using cached tzdata-2023.3-py2.py3-none-any.whl (341 kB)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.9/site-packages (from pandas) (2.8.2)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)
Installing collected packages: tzdata, pytz, numpy, pandas
Successfully installed numpy-1.26.1 pandas-2.1.1 pytz-2023.3.post1 tzdata-2023.3
WARNING: You are using pip version 21.2.4; however, version 23.3.1 is available.
You should consider upgrading via the '/Users/hk9/workspaces/workspace1/experimental_notebooks/venv/bin/python3 -m pip install --upgrade pip' command.
Collecting anndata
  Downloading anndata-0.10.2-py3-none-any.whl (118 kB)
     |████████████████████████████████| 118 kB 2.8 MB/s eta 0:00:01
Collecting h5py>=3
  Using cached h5py-3.10.0-cp39-cp39-macosx_11_0_arm64.whl (2.7 MB)
Requirement already satisfied: numpy>=1.16.5 in ./venv/lib/python3.9/site-packages (from anndata) (1.26.1)
Requirement already satisfied: exceptiongroup in ./venv/lib/python3.9/site-packages (from anndata) (1.1.3)
Requirement already satisfied: packaging>=20 in ./venv/lib/python3.9/site-packages (from anndata) (23.2)
Collecting natsort
  Using cached natsort-8.4.0-py3-none-any.whl (38 kB)
Collecting scipy>1.4
  Using cached scipy-1.11.3-cp39-cp39-macosx_12_0_arm64.whl (29.7 MB)
Requirement already satisfied: pandas!=2.1.0rc0,>=1.1.1 in ./venv/lib/python3.9/site-packages (from anndata) (2.1.1)
Collecting array-api-compat
  Downloading array_api_compat-1.4-py3-none-any.whl (29 kB)
Requirement already satisfied: tzdata>=2022.1 in ./venv/lib/python3.9/site-packages (from pandas!=2.1.0rc0,>=1.1.1->anndata) (2023.3)
Requirement already satisfied: python-dateutil>=2.8.2 in ./venv/lib/python3.9/site-packages (from pandas!=2.1.0rc0,>=1.1.1->anndata) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in ./venv/lib/python3.9/site-packages (from pandas!=2.1.0rc0,>=1.1.1->anndata) (2023.3.post1)
Requirement already satisfied: six>=1.5 in ./venv/lib/python3.9/site-packages (from python-dateutil>=2.8.2->pandas!=2.1.0rc0,>=1.1.1->anndata) (1.16.0)
Installing collected packages: scipy, natsort, h5py, array-api-compat, anndata
Successfully installed anndata-0.10.2 array-api-compat-1.4 h5py-3.10.0 natsort-8.4.0 scipy-1.11.3
WARNING: You are using pip version 21.2.4; however, version 23.3.1 is available.
You should consider upgrading via the '/Users/hk9/workspaces/workspace1/experimental_notebooks/venv/bin/python3 -m pip install --upgrade pip' command.

In [6]:
nn_ad = ad.read_h5ad("data/human_all_non_neuronal.h5ad", backed="r")
print(nn_ad.obs.shape)
nn_ad.obs.head(4)

(888263, 33)

,ROIGroup,ROIGroupCoarse,ROIGroupFine,roi,organism_ontology_term_id,disease_ontology_term_id,self_reported_ethnicity_ontology_term_id,assay_ontology_term_id,sex_ontology_term_id,development_stage_ontology_term_id,...,tissue_ontology_term_id,is_primary_data,cell_type,assay,disease,organism,sex,tissue,self_reported_ethnicity,development_stage
CellID,,,,,,,,,,,,,,,,,,,,,
10X362_3:TCAGTGAGTATTGACC,Hypothalamus,Hypothalamus,Hypothalamus,Human MN,NCBITaxon:9606,PATO:0000461,HANCESTRO:0005,EFO:0009922,PATO:0000384,HsapDv:0000123,...,UBERON:0001898,False,oligodendrocyte,10x 3' v3,normal,Homo sapiens,male,hypothalamus,European,29-year-old human stage
10X362_5:TCCGTGTGTGAAAGTT,Hypothalamus,Hypothalamus,Hypothalamus,Human MN,NCBITaxon:9606,PATO:0000461,HANCESTRO:0005,EFO:0009922,PATO:0000384,HsapDv:0000136,...,UBERON:0001898,False,oligodendrocyte,10x 3' v3,normal,Homo sapiens,male,hypothalamus,European,42-year-old human stage
10X362_5:CACGGGTAGAGCAGAA,Hypothalamus,Hypothalamus,Hypothalamus,Human MN,NCBITaxon:9606,PATO:0000461,HANCESTRO:0005,EFO:0009922,PATO:0000384,HsapDv:0000136,...,UBERON:0001898,False,oligodendrocyte,10x 3' v3,normal,Homo sapiens,male,hypothalamus,European,42-year-old human stage
10X362_5:GATTCTTGTATGTCAC,Hypothalamus,Hypothalamus,Hypothalamus,Human MN,NCBITaxon:9606,PATO:0000461,HANCESTRO:0005,EFO:0009922,PATO:0000384,HsapDv:0000136,...,UBERON:0001898,False,oligodendrocyte,10x 3' v3,normal,Homo sapiens,male,hypothalamus,European,42-year-old human stage

In [7]:
print(nn_ad.var.shape)
nn_ad.var.head()

(59357, 9)

,Biotype,Chromosome,End,Gene,Start,feature_is_filtered,feature_name,feature_reference,feature_biotype
ensembl_ids,,,,,,,,,
ENSG00000000003,n/a,chrX,100639991,TSPAN6,100627108,False,TSPAN6,NCBITaxon:9606,gene
ENSG00000000005,n/a,chrX,100599885,TNMD,100584936,False,TNMD,NCBITaxon:9606,gene
ENSG00000000419,n/a,chr20,50958555,DPM1,50934867,False,DPM1,NCBITaxon:9606,gene
ENSG00000000457,n/a,chr1,169894267,SCYL3,169849631,False,SCYL3,NCBITaxon:9606,gene
ENSG00000000460,n/a,chr1,169854080,C1orf112,169662007,False,C1orf112,NCBITaxon:9606,gene

In [8]:
ensembl_ids = nn_ad.var.index.unique().tolist()
records = list()
records.append(['ID', 'SC %', 'A rdfs:label', 'A oboInOwl:hasExactSynonym SPLIT=|'])
for ensembl_id in ensembl_ids:
    data = ['ensembl:' + ensembl_id, 'SO:0000704', nn_ad.var.loc[ensembl_id]['Gene'], '']
    records.append(data)

df = pd.DataFrame(records, columns=["ID", "TYPE", "NAME", "SYNONYMS"])

df.head()

,ID,TYPE,NAME,SYNONYMS
0,ID,SC %,A rdfs:label,A oboInOwl:hasExactSynonym SPLIT=|
1,ensembl:ENSG00000000003,SO:0000704,TSPAN6,
2,ensembl:ENSG00000000005,SO:0000704,TNMD,
3,ensembl:ENSG00000000419,SO:0000704,DPM1,
4,ensembl:ENSG00000000457,SO:0000704,SCYL3,

In [15]:
df.to_csv('data/ensg.tsv', sep="\t")